### signup
@url_dev=http://localhost:3000/v1/api

POST {{url_dev}}/signup
Content-Type: application/json
x-api-key: 8e6240e74525a904dff9e01deb1a8b58

{
    "name": "shop5",
    "email": "shop5@example.com",
    "password": "shop5@example.com"
}