### signup
@url_dev=http://localhost:3000/v1/api

Post {{url_dev}}/signup
Content-Type: application/json

{
    "name": "shop2",
    "email": "shop2@example.com",
    "password": "shop2@example.com"
}