### signup
@url_dev=http://localhost:3000/v1/api

POST {{url_dev}}/login
Content-Type: application/json
x-api-key: 36a50da8bd24dee7853520f7c9014e47

{
    "email": "shop@example.com",
    "password": "shop@example.com"
}
